services:
  gwongzho-web:
    container_name: gwongzho-landing
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "2372:3000"
    environment:
      - NODE_ENV=production